### ISSUE TITLE
How to edit the UserControl_1 doc page?

### ISSUE THREAD

**Issue by HeMinzhang** [reactiveui/website#127]
https://reactiveui.net/api/reactiveui/reactiveusercontrol_1/

I clone website to local.
But I can't find how to edit the UserControl_1 doc page.

**Comment by RLittlesII** [comment]
@HeMinzhang The documentation for the API section is actually generated by looking at xml comments the code.  Lets say you wanted to change the documentation in the remarks section.  You would have to edit the [xml comments]( https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs#L15-L42) in order to affect it.

**Comment by RLittlesII** [comment]
I believe this is related to #122

**Comment by HeMinzhang** [comment]
@RLittlesII  Thanks a million.
