### ISSUE TITLE
Style: Website expansion icon displays incorrectly

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/website#133]
I noticed that the expansion arrow that should be displayed on the website is appearing as a box.  Perviously it was an arrow that would animate based on whether the navigation item was expanded or not.

![image](https://user-images.githubusercontent.com/6969701/43732636-d28f5ca0-9977-11e8-90d7-87429039b8be.png)

**Comment by worldbeater** [comment]
Access to Font at 'https://d33wubrfki0l68.cloudfront.net/fonts/fontawesome-webfont.woff2?v=4.6.3' from origin 'https://reactiveui.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://reactiveui.net' is therefore not allowed access. The response had HTTP status code 404.

```
CDN object Not Found - Request ID: 55b2c826-dc46-48af-9b52-05bd8803a307-159127
```

It turns out FontAwesome was removed from CDN the website currently uses.
We can switch to this one: https://cdnjs.com/libraries/font-awesome
Or store the fonts locally.

**Comment by glennawatson** [comment]
Looks like the entire purpose of cdnjs is for this type of purpose so lets go with them.

**Comment by RLittlesII** [comment]
@worldbeater That is interesting (and I have confirmed that in the Chrome Developer Tools), good find.  I have several other sites built with Wyam that use the theme that aren't experiencing this issue.  So the question in my mind is, what makes us so special that we found the easter egg?

**Comment by worldbeater** [comment]
When I clone the repo and run on my local machine, the icons are back.
![image](https://user-images.githubusercontent.com/6759207/43834844-59c1764e-9b18-11e8-8469-7b3e254edf5f.png)

So probably there are some issues with deployment or host.

**Comment by daveaglick** [comment]
> Looks like the entire purpose of cdnjs is for this type of purpose so lets go with them.

+1 for cdnjs

> I have several other sites built with Wyam that use the theme that aren't experiencing this issue. So the question in my mind is, what makes us so special that we found the easter egg?

Wyam doesn't use a CDN in the default theme (that's intentional). All the assets (except for the Google Fonts) are distributed in the theme.

> When I clone the repo and run the website on my local machine, the icons are back.

Digging deeper, it looks like the ReactiveUI theme still uses local FontAwesome assets:

`_Master.cshtml`:
```
<link href="@Context.GetLink("/assets/css/font-awesome.min.css")" rel="stylesheet" type="text/css">
```

And since there's no override for `font-awesome.min.css`, it's still coming locally from the default theme. That suggests Cloudflare is swapping out the local Font Awesome files for CDN-based ones during deployment (I don't know that much about how Cloudflare works). That would also explain why it still works locally - because there's not deployment to Cloudflare and thus the asset links remain local and aren't being replaced with CDN versions.
