### ISSUE TITLE
Documentation: Add Dynamic Data

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/website#156]
Remove - https://reactiveui.net/docs/handbook/collections

Replace with a link to Dynamic Data?

This is in reference to https://github.com/reactiveui/ReactiveUI/issues/1372

Potentially Add this content?
https://github.com/RolandPheasant/DynamicData/wiki/Introduction-for-ReactiveUI-users

**Comment by worldbeater** [comment]
Maybe we should include DynamicData documentation into the ReactiveUI website? @RolandPheasant @ghuntley @glennawatson how do you look at this? Perhaps, it's worth making DynamicData a part of the ReactiveUI ecosystem. Perhaps, we should advice installing it on the Getting Started page.

**Comment by RLittlesII** [comment]
@worldbeater The above link is an article written specifically for people approaching Dynamic Data from a familiarity with ReactiveUI.  I think either linking to this, or pulling it into the main site as part of our documentation are things we should definitely consider.

**Comment by RolandPheasant** [comment]
@worldbeater I think making Dynamic Data part of the ecosystem would be a wise move, as it the suggestion about documentation

**Comment by glennawatson** [comment]
I am happy to have a small document that explains things from the RxUI users point of view but don't want a big massive bulk of documents that are already on the dynamic user website. I don't want to have a copy paste hell of having to work out whenever Roland changes the documentation and update ours.

**Comment by glennawatson** [comment]
Also I dont want a copy paste of the DD website doc either because it references rxlist interop where you can make observable change sets from a rxlist so it's not as trivial as bringing that document in.

**Comment by glennawatson** [comment]
@worldbeater and @RLittlesII 

Putting these comments in the actual task rather than in a closed PR

https://github.com/RolandPheasant/DynamicData/wiki/Introduction-for-ReactiveUI-users

That was the document Rodney meant to be brought across btw but as I mentioned would require changes to remove the discussion about how to use DynamicData with the ReativeList.

If I was doing this myself I would bring that document from the Wiki in as a base.

I would talk about how in DD everything works around a IObservable<IChangeSet> and how there are a number of internal observable aware collections, but how most of the time DD will output to a ReadonlyObservableCollection.

I would then talk about some common scenarios how RxList did stuff, eg, changes, count changes and stuff, and how to achieve the same in DD.

Then I would also talk about alternatives to the IReactiveDerivedList and the different operations.

So I potentially would making it more like a "porting" guide to the user how it works.

But I would start as the guide to that RxUI wiki page, and put it locally here, then get Roland to redirect it to our website.

Create a issue (or probably just talk to Roland) and get him to redirect his wiki page to the RxUI Website page after it's been created.

In terms of how to proceed probably best if we create a branch first, work out how we want to structure things, then do a PR over.

**Comment by glennawatson** [comment]
BTW thanks for dealing with the frustration of this one @worldbeater I know it's a bit of jumping back and forth.

**Comment by RLittlesII** [comment]
https://reactiveui.net/docs/handbook/collections/ has been updated with information on DynamicData.  Closing this issue.
