### ISSUE TITLE
Documentation: Master Detail Page Navigation

### ISSUE THREAD

**Issue by AndrewPHunter** [reactiveui/website#174]
None of the [samples](https://reactiveui.net/docs/samples/) listed on the website, nor any blog posts for that matter, detail how to implement drawer based navigation using [ReactiveMasterDetailPage](https://reactiveui.net/api/reactiveui.xamforms/reactivemasterdetailpage_1/).

This is a significant setback to Xamarin Forms based development as drawer based navigation is the defacto standard for mobile applications.

**Comment by cabauman** [comment]
Still need to add some documentation on the website but here's a sample project: https://github.com/reactiveui/ReactiveUI/pull/1741

**Comment by AndrewPHunter** [comment]
I noticed the [PR](https://github.com/reactiveui/ReactiveUI/pull/1741/commits/aab256ff6ef20cd13ef0cbb2183145f6291f9f23) uses a Navigation Page for the detail Page. Doesn't this prevent viewmodel routing? I thought the whole idea was to use RoutedViewHost to route ViewModel first?

**Comment by cabauman** [comment]
That NavigationPage is never actually used for routing at all. Just like in
the official Xamarin example, it’s sole purpose is to display the
navigation bar (for the title and hamburger button). So this example is
still doing ViewModel-first routing.

I didn’t include it in this example because this is just a single page
application (just the MasterDetail page), but if your application has
multiple pages you would use the RoutedViewHost at the root level e.g.
MainPage = new RoutedViewHost() in App.xaml.cs. Then you can utilize
ReactiveUI’s routing system.

In the official Xamarin example

https://github.com/xamarin/xamarin-forms-samples/blob/master/Navigation/MasterDetailPage/MasterDetailPageNavigation/XAML/MainPage.xaml.cs

they create a new NavigationPage *and* a new content page every time a list
item is selected but that seems like a waste to me. The example in the PR
only creates the one NavigationPage and one detail page and reuses them
from then on.

If you need an example of routing, let us know.

**Comment by cabauman** [comment]
I have a routing example in the works. I'll make another PR when it's ready.

**Comment by cabauman** [comment]
@glennawatson this can be closed now. The Master-detail example is listed on the Samples page now.
