### ISSUE TITLE
CombineLatest not trigger Func

### ISSUE THREAD

**Issue by penndai** [reactiveui/website#396]
Hi, in my codes, the Observable.CombinedLatest  doesn't triggered when one Observable produces the element.

The code snippet is below, and I set the breakpoint in the CovertedMessage, it was triggered, which means this Observable exactly produced the element. But combined observable not.

So my question is CombineLatest method combines multiple observables, if only one of the observable produce the element, should the Func be  triggered?

this.WhenAnyValue(x => x.ConvertedMessage).Where(x=>x!=null).Subscribe(x => { var msg = x.Message; });

			var initial =
				this				
				.WhenAnyValue(x => x.ConvertedMessage)
				.Where(x=>x!=null);
			
			var searchObjs =
				this
				.WhenAnyValue(x => x.SearchText)
				.Throttle(TimeSpan.FromMilliseconds(800))
				.Select(term => term)
				.DistinctUntilChanged()
				.Where(term => !string.IsNullOrEmpty(term));

			reviewFiles = Observable.CombineLatest(initial, searchObjs, (message, term) => {
				**_//I assume the below codes should be running, but not_**
				if (!string.IsNullOrEmpty(term))
				{
					// some logic here
				}
				else
				{
					//some other logic here
				}

			})

**Comment by glennawatson** [comment]
`Throttle` will be put on a different thread then you expect and will be put onto a thread pool. Put a `ObserveOn(RxApp.MainThreadScheduler)` after it.

Also worth noting we generally push questions onto StackOverflow or ask you join our Slack community rather than asking questions on GitHub.

If this doesn't solve your issue feel free to do either of StackOverflow or Slack. Our Slack community has turned off automatic signup due to a spammer so contact @anaisbetts directly on Twitter to get a invite.

**Comment by glennawatson** [comment]
Also worth noting by design `CombineObservable` only triggers when all observables have signalled a value. So in your cause the `Where(x => x != null)` would be preventing the initial trigger value. Also `WhenAnyValue` usually does DistinctUntilChanged anyway.

**Comment by penndai** [comment]
Many thanks for your reply.  I used the ObserveOn() after it. So can I understand only when all individual observable produce the element, the combined one is triggered?

Below is my question in stackoverflow
https://stackoverflow.com/questions/59890861/reactiveui-combinelatest-not-trigger-func
