### ISSUE TITLE
Add link that when user clicks on creates GitHub issue for the page

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/website#61]
This creates a product feedback loop and signifies that we want this sort of feedback.

![image](https://user-images.githubusercontent.com/127353/33195287-65bf3c6e-d12a-11e7-93d1-8a5da457b2d1.png)

See https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

https://github.com/kubernetes/website/issues/new?title=Issue%20with%20k8s.io/docs/concepts/overview/what-is-kubernetes/

ps; appears it possible to add `&body=blah` to the url to pre-fill the message template.

**Comment by dabutvin** [comment]
should this get added right below the "Edit Content" link in the sidebar?
![image](https://user-images.githubusercontent.com/5168796/33521037-67d5ed20-d77b-11e7-9931-4b9ac15c194e.png)


I can't see where this section is defined anywhere in the repo.
https://github.com/reactiveui/website/blob/master/input/_Master.cshtml#L146

**Comment by olevett** [comment]
That seems like a good place for it to go, I think this is coming from the Wyam Theme rather than the website code directly (https://github.com/Wyamio/Wyam/blob/7ac63df285968f79b6465c1418080fec7fcf8a36/themes/Docs/Samson/Shared/_Infobar.cshtml).

I think we should be able to override it, but not sure how off the top of my head.

**Comment by dabutvin** [comment]
@olevett that worked.
Thanks for the pointer
