### ISSUE TITLE
Issue with docs/handbook/commands/canceling.md

### ISSUE THREAD

**Issue by SuperJMN** [reactiveui/website#90]
In the last part, where does the CancellationToken come from? where is it created?

**EDIT:** I successfully created a Cancel command with the docs :) Sorry, I didn't see that the CancellationToken was implicit in the StartAsync call.

BTW, there's a typo: sometimes the code says "cancelable" and sometimes it is "cancellable". Please, fix it.

**Comment by RLittlesII** [comment]
@SuperJMN The various forms of the word cancel have bothered me for years.  Technically Cancelled and Canceled are both correct.  This is a divergence in the English language.  Because it is a `CancellationToken` I tend to agree that it  should be cancelled in these instances.

https://www.dictionary.com/browse/cancelable

**Comment by ghuntley** [comment]
We have a content style-guide over at https://reactiveui.net/contribute/content-style-guide/ 👍 It's based off the work that mailchimp open-sourced All content should be shaped based off the contents of the styleguide. The styleguide is the source of truth for `color` vs `colour` and how content is authored. If you think a section should be changed or burned in the style guide then send in the PR.
